-- ========================================
-- 删除 Flowable 相关表和不需要的自定义表
-- V2026062401__drop_flowable_tables.sql
-- ========================================

-- 删除 Flowable 自动创建的表（共 23 张）
DROP TABLE IF EXISTS ACT_RE_DEPLOYMENT;
DROP TABLE IF EXISTS ACT_RE_MODEL;
DROP TABLE IF EXISTS ACT_RE_PROCDEF;
DROP TABLE IF EXISTS ACT_RU_EXECUTION;
DROP TABLE IF EXISTS ACT_RU_JOB;
DROP TABLE IF EXISTS ACT_RU_TASK;
DROP TABLE IF EXISTS ACT_RU_IDENTITYLINK;
DROP TABLE IF EXISTS ACT_RU_VARIABLE;
DROP TABLE IF EXISTS ACT_RU_EVENT_SUBSCR;
DROP TABLE IF EXISTS ACT_EVT_LOG;
DROP TABLE IF EXISTS ACT_PROCDEF_INFO;
DROP TABLE IF EXISTS ACT_HI_PROCINST;
DROP TABLE IF EXISTS ACT_HI_ACTINST;
DROP TABLE IF EXISTS ACT_HI_TASKINST;
DROP TABLE IF EXISTS ACT_HI_VARINST;
DROP TABLE IF EXISTS ACT_HI_DETAIL;
DROP TABLE IF EXISTS ACT_HI_COMMENT;
DROP TABLE IF EXISTS ACT_HI_ATTACHMENT;
DROP TABLE IF EXISTS ACT_HI_IDENTITYLINK;
DROP TABLE IF EXISTS FLW_EV_PROCDEF_EVTS;
DROP TABLE IF EXISTS FLW_EVENT_DEFINITION;
DROP TABLE IF EXISTS FLW_EVENT_DEFINITION_CACHE;

-- 删除不需要的自定义表
-- wf_process_instance_copy: 使用 FlowLong 内置抄送机制
DROP TABLE IF EXISTS wf_process_instance_copy;

-- wf_process_expression: FlowLong 内置表达式功能
DROP TABLE IF EXISTS wf_process_expression;

-- wf_process_listener: FlowLong 使用拦截器机制
DROP TABLE IF EXISTS wf_process_listener;